import React, { useRef } from "react";
import { useReactToPrint } from "react-to-print";
import { MapPin, Edit3, Download } from "lucide-react";
import { ActivitiesBlock } from './ActivitiesBlock'
import { BudgetBlock } from './BudgetBlock'
import { DatesBlock } from "./DatesBlock";
import { HotelsBlock } from './HotelsBlock'
import { EditForm } from './EditForm'
import { PassengersBlock } from './PassengerBlock'
import { FlightsBlock } from './FlightsBlock'
import { DestinationBlock } from './DestinationBlock'

export const TripDetailsSidebar = ({
  agentState,
  isEditing,
  editablePlan,
  setEditablePlan,
  onEdit,
  onUpdatePlan,
  onCancelEdit,
}) => {
  const plan = agentState.plan;
  const hasState = plan || agentState.adults || agentState.flight_data;

  // 1. Create a ref for the section we want to capture as a PDF
  const contentRef = useRef(null);

  // 2. Setup the print functionality
  const handlePrint = useReactToPrint({
    contentRef,
    documentTitle: `Trip_Itinerary_${plan?.destination || 'Plan'}`,
    // This allows background graphics (colors) to be printed depending on browser settings
    onBeforeGetContent: () => {
      return Promise.resolve();
    },
    removeAfterPrint: true,
  });

  return (
    <div className="bg-white rounded-2xl shadow-lg border border-purple-100 p-6 sticky top-24 animate-in slide-in-from-right-10 duration-300">
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-lg font-bold text-gray-800 flex items-center gap-2">
          <MapPin className="w-5 h-5 text-purple-600" />
          Trip Details
        </h2>
        
        <div className="flex gap-2">
          {plan && !isEditing && (
            <button
              onClick={handlePrint}
              className="text-gray-400 hover:text-purple-600 transition-colors p-1"
              title="Download PDF"
            >
              <Download className="w-4 h-4" />
            </button>
          )}

          {plan && !isEditing && (
            <button
              onClick={onEdit}
              className="text-gray-400 hover:text-purple-600 transition-colors p-1"
              title="Edit trip details"
            >
              <Edit3 className="w-4 h-4" />
            </button>
          )}
        </div>
      </div>

      {!hasState ? (
        <p className="text-sm text-gray-500 italic">
          Details will appear as you chat...
        </p>
      ) : (
        <div className="space-y-4">
          {isEditing ? (
            <EditForm
              editablePlan={editablePlan}
              setEditablePlan={setEditablePlan}
              onSave={onUpdatePlan}
              onCancel={onCancelEdit}
            />
          ) : (
            /* 3. The 'ref' is attached here. 
               Only children of this div are included in the PDF.
            */
            <div ref={contentRef} className="space-y-4 p-2">
              
              {/* This header is hidden on screen but visible in the PDF */}
              <div className="hidden print:block mb-6 border-b pb-4">
                <h1 className="text-2xl font-bold text-purple-800">Trip Itinerary</h1>
                <p className="text-gray-600">
                  Destination: {plan?.destination || agentState.city_code || 'TBD'}
                </p>
              </div>

              {plan && (
                <>
                  <DestinationBlock plan={plan} cityCode={agentState.city_code} />
                  <DatesBlock plan={plan} />
                  <BudgetBlock plan={plan} />
                </>
              )}

              {(agentState.adults > 0 ||
                agentState.children > 0 ||
                agentState.infants > 0) && (
                <PassengersBlock agentState={agentState} />
              )}

              {agentState.flight_data && agentState.flight_data.length > 0 && (
                <FlightsBlock
                  flightData={agentState.flight_data}
                  selectedIndex={agentState.selected_flight_index}
                />
              )}

              {agentState.hotel_data &&
                agentState.hotel_data.hotels &&
                agentState.hotel_data.hotels.length > 0 && (
                  <HotelsBlock
                    hotelData={agentState.hotel_data}
                    selectedIndex={agentState.selected_hotel_index}
                  />
                )}

              {agentState.activity_data &&
                agentState.activity_data.length > 0 && (
                  <ActivitiesBlock activityData={agentState.activity_data} />
                )}
                
              {/* Footer for PDF only */}
              <div className="hidden print:block mt-8 pt-4 border-t text-sm text-gray-400 text-center">
                Generated by Travel Agent AI
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
};
