import React, { useRef } from "react";
import { useReactToPrint } from "react-to-print";
import { MapPin, Edit3, Download } from "lucide-react";
import { ActivitiesBlock } from './ActivitiesBlock'
import { BudgetBlock } from './BudgetBlock'
import { DatesBlock } from "./DatesBlock";
import { HotelsBlock } from './HotelsBlock'
import { EditForm } from './EditForm'
import { PassengersBlock } from './PassengerBlock'
import { FlightsBlock } from './FlightsBlock'
import { DestinationBlock } from './DestinationBlock'

export const TripDetailsSidebar = ({
  agentState,
  isEditing,
  editablePlan,
  setEditablePlan,
  onEdit,
  onUpdatePlan,
  onCancelEdit,
}) => {
  const plan = agentState.plan;
  const hasState = plan || agentState.adults || agentState.flight_data;

  // Ref specifically for the hidden print container
  const contentRef = useRef(null);

  const handlePrint = useReactToPrint({
    contentRef,
    documentTitle: `Trip_Itinerary_${plan?.destination || 'Plan'}`,
    pageStyle: `
      @page {
        size: A4;
        margin: 20mm 15mm;
      }
      @media print {
        * {
          -webkit-print-color-adjust: exact !important;
          print-color-adjust: exact !important;
        }
        body {
          margin: 0 !important;
          padding: 0 !important;
        }
        .print-avoid-break {
          page-break-inside: avoid !important;
          break-inside: avoid !important;
        }
      }
    `,
  });

  // Helper function to render the itinerary content
  // We pass 'isPrinting' to force accordions open in the hidden view
  const renderItineraryContent = (isPrinting = false) => (
    <>
      {/* Header: Hidden on screen (unless printing), visible in PDF */}
      <div className={`${isPrinting ? 'block' : 'hidden print:block'} mb-6 pb-4 border-b-2 border-gray-300 print-avoid-break`}>
        <h1 className="text-2xl font-bold text-gray-900 mb-2">
          Trip Itinerary
        </h1>
        <p className="text-lg text-gray-700">
          Destination: {plan?.destination || agentState.city_code || 'TBD'}
        </p>
      </div>

      {plan && (
        <>
          <div className="print-avoid-break">
            <DestinationBlock plan={plan} cityCode={agentState.city_code} destinationName={agentState.destination_name} />
          </div>
          <div className="print-avoid-break">
            <DatesBlock plan={plan} />
          </div>
          <div className="print-avoid-break">
            <BudgetBlock plan={plan} />
          </div>
        </>
      )}

      {(agentState.adults > 0 ||
        agentState.children > 0 ||
        agentState.infants > 0) && (
        <div className="print-avoid-break">
          <PassengersBlock agentState={agentState} />
        </div>
      )}

      {agentState.flight_data && agentState.flight_data.length > 0 && (
        <div className="print-avoid-break">
          <FlightsBlock
            flightData={agentState.flight_data}
            selectedIndex={agentState.selected_flight_index}
            defaultOpen={isPrinting} // <--- FORCE OPEN IF PRINTING
          />
        </div>
      )}

      {agentState.hotel_data &&
        agentState.hotel_data.hotels &&
        agentState.hotel_data.hotels.length > 0 && (
          <div className="print-avoid-break">
            <HotelsBlock
              hotelData={agentState.hotel_data}
              selectedIndex={agentState.selected_hotel_index}
              defaultOpen={isPrinting} // <--- FORCE OPEN IF PRINTING
            />
          </div>
        )}

      {agentState.activity_data &&
        agentState.activity_data.length > 0 && (
          <div className="print-avoid-break">
            <ActivitiesBlock 
              activityData={agentState.activity_data} 
              defaultOpen={isPrinting} // <--- FORCE OPEN IF PRINTING
            />
          </div>
        )}
        
      {/* Footer for PDF only */}
      {isPrinting && (
        <div className="mt-8 pt-4 border-t border-gray-300 text-center text-sm text-gray-600 print-avoid-break">
          Generated by Travel Agent AI
        </div>
      )}
    </>
  );

  return (
    <div className="bg-white rounded-2xl shadow-lg border border-purple-100 p-6 sticky top-24 animate-in slide-in-from-right-10 duration-300">
      {/* Header & Buttons */}
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-lg font-bold text-gray-800 flex items-center gap-2">
          <MapPin className="w-5 h-5 text-purple-600" />
          Trip Details
        </h2>
        
        <div className="flex gap-2">
          {plan && !isEditing && (
            <button
              onClick={handlePrint}
              className="text-gray-400 hover:text-purple-600 transition-colors p-1"
              title="Download PDF"
            >
              <Download className="w-4 h-4" />
            </button>
          )}

          {plan && !isEditing && (
            <button
              onClick={onEdit}
              className="text-gray-400 hover:text-purple-600 transition-colors p-1"
              title="Edit trip details"
            >
              <Edit3 className="w-4 h-4" />
            </button>
          )}
        </div>
      </div>

      {!hasState ? (
        <p className="text-sm text-gray-500 italic">
          Details will appear as you chat...
        </p>
      ) : (
        <div className="space-y-4">
          {isEditing ? (
            <EditForm
              editablePlan={editablePlan}
              setEditablePlan={setEditablePlan}
              onSave={onUpdatePlan}
              onCancel={onCancelEdit}
            />
          ) : (
            <>
              {/* 1. INTERACTIVE VIEW (Collapsible, Visible on Screen) */}
              <div className="space-y-6">
                {renderItineraryContent(false)}
              </div>

              {/* 2. HIDDEN PRINT VIEW (Always Expanded, Visible to Printer) */}
              <div style={{ display: "none" }}>
                <div ref={contentRef} className="p-8 space-y-6">
                  {renderItineraryContent(true)}
                </div>
              </div>
            </>
          )}
        </div>
      )}
    </div>
  );
};
